FROM node:20-alpine AS builder
ENV npm_config_user_agent="pnpm/10.26.1 npm/? node/v20.0.0 linux x64"
RUN npm install -g pnpm@10.26.1
WORKDIR /app
COPY . .
RUN pnpm install --no-frozen-lockfile
ENV PORT=3000
ENV BASE_PATH=/
ENV NODE_ENV=production
RUN pnpm --filter @workspace/bright-library run build

FROM node:20-alpine AS runner
RUN npm install -g serve
WORKDIR /app
COPY --from=builder /app/artifacts/bright-library/dist/public ./public
EXPOSE 3000
CMD ["serve", "-s", "public", "-l", "3000"]
